version: "3"
services:
  app:
    build: .
    container_name: "github-scouter"
    ports:
      - "4567:4567"
    command: bundle exec ruby lib/app.rb -o 0.0.0.0
    volumes:
      - .:/app
    tty: true
    stdin_open: true
