version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          DB_HOST: 127.0.0.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "Gemfile.lock" }}
              - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install -j4 --path vendor/bundle
      - save_cache:
          paths:
              - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rubocop
